### ISSUE TITLE
cant find class BackgroundProcess

### ISSUE THREAD

**Issue by tarsem99** [akifquddus/PHP-LiveStreaming-Library#1]
Type: Error

Message: Class 'Cocur\BackgroundProcess\BackgroundProcess' not found

Filename: /home/psmmercuryc/public_html/PHP-LiveStreaming-Library-master/application/helpers/ffmpeg_helper.php

Line Number: 61

is there any solution

**Comment by akifquddus** [comment]
Have you run composer? Cocur Library is required for the script to work. 
It has already been added to the composer.json file.
